#!/bin/bash

APP_HOME=$HOME/.setup-idx
APP_PATH=$APP_HOME/app"

if [ -d $APP_PATH/ ]; then rm -rf $APP_PATH/; fi;

if [ -d ${APP_HOME}/ ]; then rm -rf $APP_HOME/; fi;

echo "Please remove manually this content \"\$HOME/.setup-idx\" from PATH in $HOME/.bashrc\n"
